let
  TextLit = (vv as text  ) as text => 
    "'" & Text.Replace(vv, "'", "''") & "'",
  DateLit = (vv as date  ) as text =>
    "CAST(" & TextLit(Date.ToText(vv, "yyyy-MM-dd")) & " AS date)",
  DecLit  = (vv as number) as text =>
    "CAST(" & Text.From(Number.Round(vv, 2), "en-US") & " AS decimal(19,2))",
  IntLit  = (vv as number) as text =>
    "CAST(" & Text.From(Number.Round(vv, 0), "en-US") & " AS int)", 
  
  Keys0 = Excel.CurrentWorkbook(){[Name="B_Exacta"]}[Content],
  Keys = Table.TransformColumnTypes(Keys0, {
    {{ 'transforms' | mapper(keys) }}
  }, "en-US"),

  RowToSql = (row as record) as text => "(" & 
    {{ 'records' | mapper(keys) }} & ")", 
  RowsText = List.Transform(Table.ToRecords(Keys), each RowToSql(_)),
  ValuesClause = if List.IsEmpty(RowsText)
    then "VALUES ({{ 'nulls' | mapper(keys) }})" 
    else "VALUES " & Text.Combine(RowsText, ","),

  Query = "{{ 'query' | mapper(view, keys) }}",
  Database = Sql.Database("fiserv-reports.database.windows.net", "fiserv-db"),
  Result = Value.NativeQuery(Database, Query, null, [EnableFolding=true])
in
  Result