FROM mcr.microsoft.com/azure-functions/python:4-python3.12
WORKDIR /home/site/wwwroot

# ODBC drivers
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/12/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && ACCEPT_EULA=Y apt-get install -y \
        msodbcsql18 unixodbc-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Poetry and app
ENV POETRY_VERSION=2.0.1 POETRY_VIRTUALENVS_CREATE=false
COPY pyproject.toml poetry.lock ./
RUN python -m pip install --upgrade pip && \
    pip install "poetry==${POETRY_VERSION}" && \
    poetry install --only main && \
    poetry self add poetry-plugin-export && \
    poetry export -f requirements.txt --without-hashes -o azurefunc/requirements.txt
    poetry run func start --script-root azurefunc

COPY . . 
ENV PYTHONPATH="/home/site/wwwroot/src"
