FROM mcr.microsoft.com/azure-functions/python:4-python3.12
WORKDIR /home/site/wwwroot

# ODBC drivers
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/12/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && ACCEPT_EULA=Y apt-get install -y \
        msodbcsql18 unixodbc-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH="root/.local/bin:${PATH}" \
    POETRY_VERSION="2.0.1" \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR=/tmp/poetry_cache \
    PYTHONPATH="/home/site/wwwroot/src"
    
RUN /opt/python/3/bin/python3 -m pip install --upgrade pip && \
    /opt/python/3/bin/python3 -m pip install "poetry==${POETRY_VERSION}" 

COPY poetry.lock pyproject.toml ./
RUN /opt/python/3/bin/python3 -m poetry install --only main --no-root

COPY azurefunc/ ./
COPY src/ptlf/ ./src/ptlf

