# FROM python:3.12-slim
# WORKDIR /app
# COPY ./reqs_base.txt .  
# RUN pip install --trusted-host pypi.python.org -r /app/reqs_base.txt
# COPY . .

# ARG ENV_TYPE
# ARG SERVER_TYPE
# ENV ENV_TYPE ${ENV_TYPE}
# ENV SERVER_TYPE ${SERVER_TYPE}

# EXPOSE 80
# CMD ["python", "-m", "src.app.main"]

FROM mcr.microsoft.com/azure-functions/python:4-python3.12
WORKDIR /home/site/wwwroot

RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/12/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && ACCEPT_EULA=Y apt-get install -y \
        msodbcsql18 unixodbc-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY src/requirements.txt ./requirements.txt
RUN python -m pip install --upgrade pip && \
    pip install -r ./requirements.txt

COPY src/ ./

