"""Ajustes manuales de SQLACODEGEN
Revision ID: 354e49523da4
Revises: 09fd00380b88
Create Date: 2026-06-18 12:19:10.186976
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
# pylint: disable=line-too-long
# pylint: disable=no-member

revision: str = '354e49523da4'
down_revision: Union[str, Sequence[str], None] = '09fd00380b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_PTLF_track_date', table_name='PTLF_track')
    op.alter_column('PTLF_track', 'date_file', 
        existing_type=sa.Date(), nullable=False)
    op.create_index('IX_PTLF_track_date', 'PTLF_track', ['date_file'],
        mssql_clustered=False)    
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_PTLF_track_date', table_name='PTLF_track')
    op.alter_column('PTLF_track', 'date_file', 
        existing_type=sa.DATE(), nullable=True)
    op.create_index('IX_PTLF_track_date', 'PTLF_track', ['date_file'],
        mssql_clustered=False)    
    # ### end Alembic commands ###
