"""Baseline from SQLACODEGEN
Revision ID: 09fd00380b88
Revises: 
Create Date: 2026-06-18 12:13:36.750689
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
# pylint: disable=line-too-long
# pylint: disable=no-member

revision: str = '09fd00380b88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
