import pyodbc

from config import (
    AZURE_CLIENT_ID,
    AZURE_CLIENT_SECRET,
    SERVER,
    DATABASE,
) 

# Conexión con autenticación por Service Principal
conn_str = (
    "Driver=/opt/homebrew/lib/libmsodbcsql.17.dylib;"
    f"Server={SERVER};"
    f"Database={DATABASE};"
    "Authentication=ActiveDirectoryServicePrincipal;"
    f"UID={AZURE_CLIENT_ID};"
    f"PWD={AZURE_CLIENT_SECRET};"
    "Encrypt=yes;"
    "TrustServerCertificate=yes;"
)

print("🔍 Variables cargadas:")
print(f"SERVER={SERVER}")
print(f"DATABASE={DATABASE}")
print(f"CLIENT_ID={AZURE_CLIENT_ID}")
print(f"SECRET is set: {AZURE_CLIENT_SECRET is not None}")

conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

# Crear tabla ptlf_lo
cursor.execute("""
CREATE TABLE ptlf_lo (
    [ID_OPERACION] NVARCHAR(255),
    [ID_VERSION] NVARCHAR(255),
    [SECUENCIA] NVARCHAR(255),
    [ID_OPERACION_BIS] NVARCHAR(255),
    [ID_OPERACION_HIS] NVARCHAR(255),
    [FECHA_REPORTE] NVARCHAR(255),
    [FECHA_VALOR] NVARCHAR(255),
    [FECHA_VENCIMIENTO] NVARCHAR(255),
    [FECHA_EMISION] NVARCHAR(255),
    [FECHA_PAGO_INTERES] NVARCHAR(255),
    [FECHA_PAGO_CAPITAL] NVARCHAR(255),
    [ID_CLIENTE] NVARCHAR(255),
    [ID_CONTRAPARTE] NVARCHAR(255),
    [ID_CONTRAPARTE_HIS] NVARCHAR(255),
    [ID_GARANTE] NVARCHAR(255),
    [ID_SECTOR_INST] NVARCHAR(255),
    [ID_SECTOR_CONTRAPARTE] NVARCHAR(255),
    [ID_TIPO_PERSONA] NVARCHAR(255),
    [ID_SUB_TIPO_PERSONA] NVARCHAR(255),
    [ID_ENTIDAD] NVARCHAR(255),
    [ID_TIPO_ENTIDAD] NVARCHAR(255),
    [ID_TIPO_OPERACION] NVARCHAR(255),
    [ID_SUB_TIPO_OPERACION] NVARCHAR(255),
    [ID_MONEDA] NVARCHAR(255),
    [ID_TIPO_CAMBIO] NVARCHAR(255),
    [TIPO_TASA] NVARCHAR(255),
    [TASA_INTERES] NVARCHAR(255),
    [MONTO_ORIGINAL] NVARCHAR(255),
    [SALDO_OPERACION] NVARCHAR(255),
    [TIPO_GARANTIA] NVARCHAR(255),
    [ESTADO_OPERACION] NVARCHAR(255),
    [OPERACION_RELEVANTE] NVARCHAR(255),
    [CLASIFICACION_RIESGO] NVARCHAR(255),
    [PROVISION_OPERACION] NVARCHAR(255),
    [VALOR_DESEMBOLSADO] NVARCHAR(255),
    [VALOR_RECUPERADO] NVARCHAR(255),
    [FECHA_DESEMBOLSO] NVARCHAR(255),
    [FECHA_RECUPERACION] NVARCHAR(255),
    [TIPO_CAMBIO_PACTADO] NVARCHAR(255),
    [FECHA_TASA_FIJA] NVARCHAR(255),
    [GARANTIA_REAL] NVARCHAR(255),
    [GARANTIA_PERSONAL] NVARCHAR(255),
    [TIPO_PRODUCTO] NVARCHAR(255),
    [ID_TIPO_CLIENTE] NVARCHAR(255),
    [CODIGO_SECTORIAL] NVARCHAR(255),
    [ID_TIPO_INSTITUCION] NVARCHAR(255),
    [ID_CATEGORIA_CARTERA] NVARCHAR(255),
    [ID_MODALIDAD] NVARCHAR(255),
    [CALIFICACION_CARTERA] NVARCHAR(255),
    [FECHA_ULTIMA_CLASIFICACION] NVARCHAR(255),
    [PORCENTAJE_COBERTURA] NVARCHAR(255),
    [ID_GARANTIA] NVARCHAR(255),
    [CLASIFICACION_INTERNA] NVARCHAR(255)
);
""")

conn.commit()
print("✅ Tabla 'ptlf_lo' creada correctamente.")
conn.close()
