let
  ReadName = (nm as text) as nullable any =>
    try Excel.CurrentWorkbook(){[Name=nm]}[Content]{0}[Column1] 
    otherwise null,
  OptText = (v as any) as nullable text =>
    if v = null then null 
    else let t = Text.Trim(Text.From(v)) 
      in if t = "" then null else t,
  OptDate = (v as any) as nullable date =>
    if v = null then null 
    else try Date.From(v) otherwise null, 
  OptNumber = (v as any) as nullable number =>
    if v = null then null   
    else let t = Text.Trim(Text.From(v))
      in if t = "" then null else try Number.From(t) otherwise null,

  Params = [
    Tarjeta = OptText(ReadName("par_Tarjeta")),
		TipoAuth = OptNumber(ReadName("par_Tipo_Auth")),
		FechaTrans = OptDate(ReadName("par_Fecha_Trans")),
		CodigoAprov = OptText(ReadName("par_Codigo_Aprov")) ], 
  
  Db = Sql.Database("tcp:fiserv-reports.database.windows.net,1433", "fiserv-db"),
  Filter0 = Db{[Schema = "dbo", Item = ""]}[Data],
  Filter1 = if Params[Tarjeta] <> null 
		then Table.SelectRows(Filter0, each [Tarjeta] = Params[Tarjeta]) 
		else Filter0,
	Filter2 = if Params[TipoAuth] <> null 
		then Table.SelectRows(Filter1, each [TipoAuth] = Params[TipoAuth]) 
		else Filter1,
	Filter3 = if Params[FechaTrans] <> null 
		then Table.SelectRows(Filter2, each [FechaTrans] = Params[FechaTrans]) 
		else Filter2,
	Filter4 = if Params[CodigoAprov] <> null 
		then Table.SelectRows(Filter3, each [CodigoAprov] = Params[CodigoAprov]) 
		else Filter3,
  Tops99 = Table.FirstN(Filter0, 9999)
in Tops99