let
  ReadName = (nm as text) as nullable any =>
      try Excel.CurrentWorkbook(){[Name=nm]}[Content]{0}[Column1] otherwise null,
  OptText = (v as any) as nullable text =>
      if v = null then null 
      else let t = Text.Trim(Text.From(v)) 
        in if t = "" then null else t,
  OptDate = (v as any) as nullable date =>
      if v = null then null else try Date.From(v) otherwise null, 
  OptNum = (v as any) as nullable number =>
    if v = null then null
    else let t = Text.Trim(Text.From(v))
        in if t = "" then null
          else try Number.From(t) otherwise null, 

  Params = [tarjeta = OptText(ReadName("par_tarjeta")), 
    codigo_aprov = OptNum(ReadName("par_codigo_aprov")), 
    fecha_trans = OptDate(ReadName("par_fecha_trans")), 
    tipo_auth = OptNum(ReadName("par_tipo_auth"))], 

  Db = Sql.Database("tcp:fiserv-reports.database.windows.net,1433", "fiserv-db"), 
  Filter0 = Db{[Schema = "dbo", Item = "v_PTLF_Fraudes"]}[Data], 
  Filter1 = if Params[tarjeta] <> null then 
    Table.SelectRows(Filter0, each [Tarjeta] = Params[tarjeta]) else Filter0, 
  Filter2 = if Params[codigo_aprov] <> null then 
    Table.SelectRows(Filter1, each [Codigo_Aprov] >= Params[codigo_aprov]) else Filter1, 
  Filter3 = if Params[fecha_trans] <> null then 
    Table.SelectRows(Filter2, each [Fecha_Trans] = Params[fecha_trans]) else Filter2, 
  Filter4 = if Params[tipo_auth] <> null then 
    Table.SelectRows(Filter3, each [Tipo_Auth] = Params[tipo_auth]) else Filter3, 
  Tops99 = Table.FirstN(Filter4, 9999)
in
  Tops99