let
  TextLit = (vv as text  ) as text => 
    "'" & Text.Replace(vv, "'", "''") & "'",
  DateLit = (vv as date  ) as text =>
    "CAST(" & TextLit(Date.ToText(vv, "yyyy-MM-dd")) & " AS date)",
  DecLit  = (vv as number) as text =>
    "CAST(" & Text.From(Number.Round(vv, 2), "en-US") & " AS decimal(19,2))",
  IntLit  = (vv as number) as text =>
    "CAST(" & Text.From(Number.Round(vv, 0), "en-US") & " AS int)", 
  
  Keys0 = Excel.CurrentWorkbook(){[Name="B_Exacta"]}[Content],
  Keys = Table.TransformColumnTypes(Keys0, {
      {"Tarjeta", type text},
      {"Codigo_Aprov",  type text},
      {"Fecha_Trans",  type date},
      {"Tipo_Auth", type number}
    }, "en-US"),

  RowToSql = (row as record) as text => "(" &
      TextLit(Record.Field(row, "Tarjeta"))      & "," &
      TextLit(Record.Field(row, "Codigo_Aprov")) & "," &
      DateLit(Record.Field(row, "Fecha_Trans" )) & "," &
      IntLit (Record.Field(row, "Tipo_Auth"   )) & ")", 
  RowsText = List.Transform(Table.ToRecords(Keys), each RowToSql(_)),
  ValuesClause =
      if List.IsEmpty(RowsText)
      then "VALUES (NULL, NULL, NULL, NULL)"
      else "VALUES " & Text.Combine(RowsText, ","),
  
  Qry = "
    ; SELECT t.*
    FROM dbo.v_PTLF_Fraudes AS t
    JOIN ("& ValuesClause & "
      ) AS k(Tarjeta, Codigo_Aprov, Fecha_Trans, Tipo_Auth) 
      ON t.Tarjeta = k.Tarjeta
     AND t.Codigo_Aprov = k.Codigo_Aprov
     AND t.Fecha_Trans = k.Fecha_Trans
     AND t.Tipo_Auth = k.Tipo_Auth",
  Db = Sql.Database("fiserv-reports.database.windows.net", "fiserv-db"),
  Result = Value.NativeQuery(Db, Qry, null, [EnableFolding=true])
in
  Result