let
  ReadName = (nm as text) as nullable any =>
      try Excel.CurrentWorkbook(){[Name=nm]}[Content]{0}[Column1] otherwise null,
  OptText = (v as any) as nullable text =>
      if v = null then null 
      else let t = Text.Trim(Text.From(v)) 
        in if t = "" then null else t,
  OptDate = (v as any) as nullable date =>
      if v = null then null else try Date.From(v) otherwise null, 
  OptNum = (v as any) as nullable number =>
    if v = null then null
    else let t = Text.Trim(Text.From(v))
        in if t = "" then null
          else try Number.From(t) otherwise null

, Params = [pTarjeta = OptText(ReadName("num_tarjeta")), 
    pInicio  = OptDate(ReadName("f_inicio")), 
    pFinal   = OptDate(ReadName("f_final")), 
    autorizacion = OptText(ReadName("num_autorizacion")), 
    importe_min = OptNum(ReadName("importe_min")), 
    import_max = OptNum(ReadName("importe_max"))]

, Db = Sql.Database("tcp:fiserv-reports.database.windows.net,1433", "fiserv-db")
, BaseView = Db{[Schema = "dbo", Item = "v_PTLF_Token"]}[Data]
, FilterCard = if Params[pTarjeta] <> null then 
    Table.SelectRows(BaseView, each [num_tarjeta] = Params[pTarjeta]) else BaseView
, FilterDateMin = if Params[pInicio] <> null then 
    Table.SelectRows(FilterCard, each [f_posteo] >= Params[pInicio]) else FilterCard
, FilterAuth = if Params[autorizacion] <> null then 
    Table.SelectRows(FilterDateMin, each [num_autorizacion] = Params[autorizacion]) else FilterDateMin
, Tops = FilterAuth.FirstN(9999)
, WTypes = Table.TransformColumnTypes(FilterDateMin, {{"f_posteo", type date}
})
  
in
  WTypes