let
  Keys0 = Excel.CurrentWorkbook(){[Name="B_Exacta"]}[Content],

  // Normalize types (text, date, number). Keep it simple & explicit.
  Keys = Table.TransformColumnTypes(Keys0,{
      {"FID", type text},
      {"Tarjeta",  type number},
      {"Afiliacion",  type text},
      {"F_Posteo", type date}
    }, "en-US"),

  // --- Safe SQL literals -----------------------------------
  TxtQuote = (ss as text  ) as text => 
      "'" & Text.Replace(ss, "'", "''") & "'",
  DateLit  = (dd as date  ) as text =>
      "CAST(" & TxtQuote(Date.ToText(dd, "yyyy-MM-dd")) & " AS date)",
  DecLit   = (nn as number) as text =>
      "CAST(" & Text.From(Number.Round(nn, 2), "en-US") & " AS decimal(19,2))",
  IntLit   = (ii as number) as text =>
      "CAST(" & Text.From(Number.Round(ii, 0), "en-US") & " AS int)", 
  
  RowToSql = (row as record) as text => "(" &
      TxtQuote(Record.Field(row, "FID")) & "," &
      DateLit (Record.Field(row, "Tarjeta"   )) & "," &
      TxtQuote(Record.Field(row, "Afiliacion" )) & "," &
      DecLit  (Record.Field(row, "F_Poste0"   )) & ")", 
  RowsText = List.Transform(Table.ToRecords(Keys), each RowToSql(_)),
  ValuesClause =
      if List.IsEmpty(RowsText)
      then "VALUES (NULL, NULL, NULL, NULL, NULL)"  // harmless empty guard
      else "VALUES " & Text.Combine(RowsText, ","),

  Qry = "
    ; SELECT t.*
    FROM dbo.v_PTLF_Fraudes AS t
    JOIN ("& ValuesClause & "
      ) AS k(FID, Tarjeta, Afiliacion, Fecha_Posteo) 
      ON t.FID = k.FID
     AND t.Tarjeta = k.Tarjeta
     AND t.Afiliacion = k.Afiliacion
     AND t.Fecha_Posteo = k.Fecha_Posteo",
  Qry2 = "
    ; WITH k(FID, Tarjeta, Afiliacion, Fecha_Posteo) 
    AS ( SELECT * FROM (" & ValuesClause & "
       ) v(FID, Tarjeta, Afiliacion, Fecha_Posteo)
    SELECT t.*
    FROM dbo.v_PTLF_Fraudes AS t
    JOIN k
      ON t.FID = k.FID
     AND t.Tarjeta = k.Tarjeta
     AND t.Afiliacion = k.Afiliacion
     AND t.Fecha_Posteo = k.Fecha_Posteo",
  
  // 2) Execute as a native query (runs entirely on SQL Server, uses your composite index)
  Db = Sql.Database("fiserv-reports.database.windows.net", "fiserv-db"),
  Result = Value.NativeQuery(Db, Qry, null, [EnableFolding=true])
in
  Result