let
  // Para leer parámetros. 
  ReadName = (nm as text) as nullable any =>
      try Excel.CurrentWorkbook(){[Name=nm]}[Content]{0}[Column1] otherwise null,
  OptText = (v as any) as nullable text =>
      if v = null then null 
      else let t = Text.Trim(Text.From(v)) 
        in if t = "" then null else t,
  OptDate = (v as any) as nullable date =>
      if v = null then null else try Date.From(v) otherwise null, 
  OptNum = (v as any) as nullable number =>
    if v = null then null
    else let t = Text.Trim(Text.From(v))
        in if t = "" then null
          else try Number.From(t) otherwise null

  // Los parámetros
, Params = [fid = OptText(ReadName("par_fid")), 
    tarjeta  = OptNum(ReadName("par_tarjeta")), 
    afiliacion = OptText(ReadName("par_afiliacion")), 
    posteo = OptDate(ReadName("par_posteo"))]

// las fuentes de datos
, Db = Sql.Database("tcp:fiserv-reports.database.windows.net,1433", "fiserv-db")
, BaseView = Db{[Schema = "dbo", Item = "v_PTLF_Fraudes"]}[Data]
, FilterFID = if Params[fid] <> null then 
    Table.SelectRows(BaseView, each [FID] = Params[fid]) else BaseView
, FilterTarjeta = if Params[tarjeta] <> null then 
    Table.SelectRows(FilterFID, each [Tarjeta] >= Params[tarjeta]) else FilterFID
, FilterAfiliacion = if Params[afiliacion] <> null then 
    Table.SelectRows(FilterTarjeta, each [Afiliacion] = Params[afiliacion]) else FilterTarjeta
, FilterPosteo = if Params[posteo] <> null then 
    Table.SelectRows(FilterAfiliacion, each [Fecha_Posteo] = Params[posteo]) else FilterAfiliacion
, Tops99 = Table.FirstN(FilterPosteo, 9999)
, WTypes = Table.TransformColumnTypes(Tops99, {{"Fecha_Posteo", type date}
    , {"Fecha_Trans", type date}, {"Monto", Currency.Type}
})
  
in
  WTypes